language: java
jdk: oraclejdk8
sudo: false
install: "/bin/true"
script:
- "./ci/script/build.sh"
after_success:
- "./ci/script/deploy.sh"
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - LOC=ci/secring.gpg
  - secure: DDiKMLP4AwfpelxmKdTUH4k48UUA7Tgny1LKub/QMaLKENcOetL5e04ad0YK3Z8v+Uf+KJpocItGKOnbELPRZYQvkU+ZKsnarKs4Lt5lXlVYp9vUeHqdokaNoyW/vJXKG2AwsNdUptlvunJidF5LONbjkOCj4zRgfyNZ7cUQNgLNEGO1ZLfLfDr489fplvppgIpLGs6/YLmHCm6rWrXR1AaJBltY4ZwFn9MPnMtNO5zELGvVzl9ceN4kSfREuzVH/7jJsKd/yPRVQjfRHfnPXEY4GYfGWlsAkLOUXRm7Yw++isJNcez27Zuo5DDEZpqqLK2etTwQI1C0QBdRSgdljFRSGd3A3xFtat88hq9XumOIB/o88V8QmZcs1Ln0YOXTuk7zxEYdmpg4o2d5fCr5T8T1O8DDvtJSJcjUNEyt5F3lpwE5g67UVVoG767RJm9EheU9m4FvMJMstkFd6NGnCvTvFeMhPC8oQFESKI9XWlAc5aM63e0cRBE7S4DURLe3olwkXVaN8fgI1D05HVyKOoHnWupv20x1IBl9kl6IDa8aDUeEBBvaxwqnogfWlgf0Bn6pmmi6BVP4Z+gdRS+2EuYwVaeO5CYcNeCgzb/QZNip1Lnx3dzrVUzfyzGV1eH5TsEfMs2mSKr+wd6F8CP0tjgoc+x0HOaw4AmKs95v8ow=
  - secure: xWyONZgtnZ/LwSfdG3NUphe1AruY9XJ1WnKQ8AymqLyLWpQlmhSsHR+9WBhKHvEvfbcPIBSsDhfZ2SSuFLMpGaqERllQTOf6M4yOvmieIsG97cKT6CdunB7EaQtfaqAr3Jy/BWTmqyn4SdbppvmyTZSc8xjKem0VEwOK+/rmiQLPgSV6DEDwNUhglCJ6IKdJe2hIAF3/3jU019k8fyyW49Gx6wzrduZBxV9m7sYkRI8Dv7D/0HONO7Q7yu/iZGny6U4ouEyae4MEz3jU5EDlP899z0VTQGsjDEdCEEJqyK79XGW3eOX+zi6W5GtjIZEJKpw7LXGh1W1gn7ktTx2EleSQS+5MBHzU/DUEwEp+nQJ8jb4ghY58GyBw/+DsAPbqQbdNdzWG70c2xqHPuXYkJzXvOeU1LAx1eDyJU40e2eKJ/nSXX030pSRoeiA1I02HyczYncV86+RdjQhwydFC+hjRzYeBgPxJ+S0tGWSRD800Jf/CrII3G0TRuLe+q+am+uoHPmlR+uaDO6K1e0ganGAR3aas3uFTDUF0sBRJSP3MBjih6WApL4eQV30RdDZVchIrZEdy+qlo/Ch0FzxJAXcRvt+eoqt+vkt31dx18bmrpR23p8KPEtcA6c4FcuqwQqMypBH1Rr+0tsLh5wtChkZe3IRnMa2hWXW1CFQRdxM=
